version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: custodia-db
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust

    ports:
      - "5432:5432"

    volumes:
      - "/Users/lucasiqueira/Library/CloudStorage/OneDrive-Pessoal/Documentos/Financeiro/03_Controle Pessoal/Custódia/Database:/var/lib/postgresql/data"

  custodia-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: custodia-api:latest
    environment:
      TZ: America/Sao_Paulo # Define o fuso horário para o container
      PGTZ: America/Sao_Paulo # Define o fuso horário para o PostgreSQL
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:${DB_PORT}/${DB_NAME}"
      QUARKUS_DATASOURCE_USERNAME: ${DB_USER}
      QUARKUS_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    container_name: custodia-api
    working_dir: /workspace
    volumes:
      - ./:/workspace:cached
      - ~/.m2:/root/.m2
    command: ["sh", "-c", "./mvnw -DskipTests package && java -Dquarkus.http.host=0.0.0.0 -jar target/quarkus-app/quarkus-run.jar"]
    env_file:
      - .env
    depends_on:
      - postgres
