version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: custodia-db
    restart: unless-stopped

    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - "/Users/lucasiqueira/Library/CloudStorage/OneDrive-Pessoal/Documentos/Financeiro/03_Controle Pessoal/Cust√≥dia/Database:/var/lib/postgresql/data"

  # custodia-api:
  #   image: maven:3.9.4-jdk-21
  #   container_name: custodia-api
  #   working_dir: /workspace
  #   volumes:
  #     - ./:/workspace:cached
  #     - ~/.m2:/root/.m2
  #   command: ["./mvnw", "-Dquarkus.http.host=0.0.0.0", "quarkus:dev"]
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - .env
  #   environment:
  #     QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:5432/${DB_NAME}"
  #     QUARKUS_DATASOURCE_USERNAME: ${DB_USER}
  #     QUARKUS_DATASOURCE_PASSWORD: ${DB_PASSWORD}
  #   depends_on:
  #     - postgres
